[package]
name = "minecraft-command-types"
version = "0.1.0"
edition = "2024"

[dependencies]
nonempty = "0.12.0"
itertools = "0.14.0"
ordered-float = "5.1.0"
strum = { version = "0.27.2", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"], optional = true }
serde_json = { version = "1.0.145", optional = true }

[features]
default = []
serde = ["dep:serde", "serde_json", "ordered-float/serde"]